[package]
name = "crypto-gain-loss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockfrost = "1.0.1"
chrono = "0.4.31"
clippy = "0.0.302"
color-eyre = "0.6.2"
tokio = "1.35.1"
